### ISSUE TITLE
when yarn dev, app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by hamin7** [hamin7/Muckstagram#1]
When npm init, yarn init and yarn dev, error like below

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/hamin/Documents/Muckstagram/node_modules/@babel/preset-env/lib/index.js")
    at throwVersionError (/Users/hamin/Documents/Muckstagram/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/hamin/Documents/Muckstagram/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/hamin/Documents/Muckstagram/node_modules/@babel/preset-env/lib/index.js:191:7)
    at /Users/hamin/Documents/Muckstagram/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/hamin/Documents/Muckstagram/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/hamin/Documents/Muckstagram/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/hamin/Documents/Muckstagram/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/hamin/Documents/Muckstagram/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/hamin/Documents/Muckstagram/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/hamin/Documents/Muckstagram/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/hamin/Documents/Muckstagram/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hamin/Documents/Muckstagram/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at Object.<anonymous> (/Users/hamin/Documents/Muckstagram/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
[nodemon] app crashed - waiting for file changes before starting...

If anyone have a solution, give it to me plz...

**Comment by hamin7** [comment]
We could add run "yarn why babel-core" (when using yarn) or "npx npm-why @babel/helpers" (when using npm) to see why the old version of Babel is installed. to the error message.

**Comment by hamin7** [comment]
likely related to babel-preset-react-native-stage-0, which uses v6 plugins.

**Comment by hamin7** [comment]
I think you need to add babel-core: ^7.0.0-bridge.0

Try this:

npm install --save-dev "babel-core@^7.0.0-bridge.0"

**Comment by hamin7** [comment]
The babel-core bridge is the right answer there's something about this in babel-upgrade's readme file (look up jest).

https://github.com/babel/babel-upgrade/blob/master/readme.md
